version: '3.9'

services:

  app_sofka:
    image: alexer1515/bankingapp
    ports:
      - '8086:8086'
    links:
      - mongo_sofka
    environment:
      - mongo.uri=mongodb://mongo_sofka:27017
    depends_on:
      - mongo_sofka


  mongo_sofka:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data_mongo_sofka:/data/db


  logs_sofka:
    image: alexer1515/logsapp
    ports:
      - '8089:8089'
    links:
      - mongo_sofka
    environment:
      - mongo.uri=mongodb://mongo_sofka:27017
    depends_on:
      - mongo_sofka



volumes:
  data_mongo_sofka: