apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sofka-web
  template:
    metadata:
      labels:
        app: sofka-web
    spec:
      containers:
        - name: sofka-web
          image: alexer1515/bankingapp #Defino la imagen
          ports:
            - containerPort: 8086
          env:
            - name: mongo.uri
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: mongo.uri

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: sofka-web
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 30005